Id: openmedia.4kvideodownloader
Publisher: OpenMedia LLC
Name: 4K Video Downloader Free Edition
Version: 4.12.4.0
License: non-commercial
Author: ErisuKuraku
InstallerType: msi
LicenseUrl: https://www.4kdownload.com/agreement/freeware
AppMoniker: 4kvideodownloader
ManifestVersion: 0.1.0
Tags: downloader
Description: Free video downloader for sites such as YouTube and TikTok.
Homepage: https://www.4kdownload.com/products/product-videodownloader
Installers:
  - Arch: x64
    InstallerType: MSI
    Url: https://dl.4kdownload.com/app/4kvideodownloader_4.12.4_x64.msi
    Sha256: 553D4A3EFA6D06A62E640E3D910AAA5A5ABECC9D828B683C23F7E22E08CA1AF5
